{% set version = "1.24.0" %}

package:
  name: wayland
  version: {{ version }}

source:
  url: https://gitlab.freedesktop.org/wayland/wayland/-/archive/{{ version }}/wayland-{{ version }}.tar.bz2
  sha256: ef9224f1a8b6dbd3049a2e51a547abb7e89612414c192a4349f3c83c7f553672

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('wayland', max_pin='x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
    - meson
    - ninja
  host:
    - expat
    - libffi

test:
  commands:
    - wayland-scanner --help
    - test -f ${PREFIX}/lib/libwayland-egl.so
    - test -f ${PREFIX}/lib/libwayland-client.so
    - test -f ${PREFIX}/lib/libwayland-cursor.so
    - test -f ${PREFIX}/lib/libwayland-server.so
    - test -f ${PREFIX}/lib/pkgconfig/wayland-egl.pc
    - test -f ${PREFIX}/lib/pkgconfig/wayland-client.pc
    - test -f ${PREFIX}/lib/pkgconfig/wayland-cursor.pc
    - test -f ${PREFIX}/lib/pkgconfig/wayland-server.pc
    - test -f ${PREFIX}/include/wayland-egl.h
    - test -f ${PREFIX}/include/wayland-client.h
    - test -f ${PREFIX}/include/wayland-cursor.h
    - test -f ${PREFIX}/include/wayland-server.h

about:
  home: https://wayland.freedesktop.org
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Base libraries for the Wayland rendering architecture
  description: "Wayland is a project to define a protocol for a compositor to talk to
    its clients as well as a library implementation of the protocol.  The
    compositor can be a standalone display server running on Linux kernel
    modesetting and evdev input devices, an X application, or a wayland
    client itself.  The clients can be traditional applications, X servers
    (rootless or fullscreen) or other display servers."
  doc_url: https://wayland.freedesktop.org/docs/html
  dev_url: https://gitlab.freedesktop.org/wayland/wayland

extra:
  recipe-maintainers:
    - hmaarrfk
    - pkgw
